apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: hello-trigger-binding
spec:
  params:
    - name: repository
      value: $(params.repository) 
    - name: branch
      value: $(params.branch) 
