apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: hello-trigger-binding
spec:
  params:
    - name: repository
      value: https://github.com/savya-alla/Tekton-Tutorial
    - name: branch
      value: master
